document.getElementById('boton_mostrar').onclick = function mostrar_todo(){
    document.getElementById('inf_perfil').style.display = 'block';
    document.getElementById('inf_Acerca').style.display = 'block';
    document.getElementById('inf_Contacto').style.display = 'block';
    document.getElementById('inf_Idiomas').style.display = 'block';
    document.getElementById('exp1').style.display = 'block';
    document.getElementById('exp2').style.display = 'block';
    document.getElementById('exp3').style.display = 'block';
    document.getElementById('boton_mostrar').style="display:none";
    document.getElementById('boton_ocultar').style="display:block";
    document.getElementById('boton_perfiloff').style="display:none";
    document.getElementById('boton_perfil').style="display:block";
    document.getElementById('boton_acercaoff').style="display:none";
    document.getElementById('boton_acerca').style="display:block";
    document.getElementById('boton_contactooff').style="display:none";
    document.getElementById('boton_contacto').style="display:block";
    document.getElementById('boton_idiomasoff').style="display:none";
    document.getElementById('boton_idiomas').style="display:block";
    document.getElementById('boton_exp1off').style="display:none";
    document.getElementById('boton_exp1').style="display:block";
    document.getElementById('boton_exp2off').style="display:none";
    document.getElementById('boton_exp2').style="display:block";
    document.getElementById('boton_exp3off').style="display:none";
    document.getElementById('boton_exp3').style="display:block";
    }